export const pilgrimageRouteTheme = {
  name: 'PilgrimageRoute',
  colors: {
    surface: '#fbf7f2',
    surfaceDim: '#e3dbd3',
    surfaceBright: '#ffffff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f5efe8',
    surfaceContainer: '#eee7dc',
    surfaceContainerHigh: '#e8dfd4',
    surfaceContainerHighest: '#dfd3c6',
    onSurface: '#1a1d21',
    onSurfaceVariant: '#6f625d',
    inverseSurface: '#2f3136',
    inverseOnSurface: '#f6f2ed',
    outline: '#d6c8b8',
    outlineVariant: '#eadfd1',
    surfaceTint: '#6a003f',
    primary: '#6a003f',
    onPrimary: '#ffffff',
    primaryContainer: '#f9e6f0',
    onPrimaryContainer: '#6a003f',
    inversePrimary: '#ffb0cf',
    secondary: '#7c6f67',
    onSecondary: '#ffffff',
    secondaryContainer: '#efe7dc',
    onSecondaryContainer: '#62564f',
    tertiary: '#756cf6',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ece8ff',
    onTertiaryContainer: '#5d53d8',
    background: '#fbf7f2',
    onBackground: '#1a1d21',
    surfaceVariant: '#eee7dc',
  },
  spacing: {
    xs: 4,
    sm: 12,
    md: 24,
    lg: 48,
    xl: 80,
  },
  radii: {
    sm: 4,
    base: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    fontFamily: 'Manrope',
  },
} as const;
