export const pilgrimageRouteTheme = {
  name: 'PilgrimageRoute',
  colors: {
    surface: '#f8f9fa',
    surfaceDim: '#d9dadb',
    surfaceBright: '#f8f9fa',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f4f5',
    surfaceContainer: '#edeeef',
    surfaceContainerHigh: '#e7e8e9',
    surfaceContainerHighest: '#e1e3e4',
    onSurface: '#191c1d',
    onSurfaceVariant: '#564149',
    inverseSurface: '#2e3132',
    inverseOnSurface: '#f0f1f2',
    outline: '#897079',
    outlineVariant: '#ddbfc8',
    surfaceTint: '#ae226f',
    primary: '#6a003f',
    onPrimary: '#ffffff',
    primaryContainer: '#93005a',
    onPrimaryContainer: '#ff9dc6',
    inversePrimary: '#ffb0cf',
    secondary: '#785900',
    onSecondary: '#ffffff',
    secondaryContainer: '#fdc003',
    onSecondaryContainer: '#6c5000',
    tertiary: '#5c1a45',
    onTertiary: '#ffffff',
    tertiaryContainer: '#78315c',
    onTertiaryContainer: '#fa9fd0',
    background: '#f8f9fa',
    onBackground: '#191c1d',
    surfaceVariant: '#e1e3e4',
  },
  spacing: {
    xs: 4,
    sm: 12,
    md: 24,
    lg: 48,
    xl: 80,
  },
  radii: {
    sm: 4,
    base: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    fontFamily: 'Manrope',
  },
} as const;
